spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # TODO: Add route configurations
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always