spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # TODO: Add Git repository configuration
          uri: file:///config-repo
          default-label: main

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always